### ISSUE TITLE
Google SSO doc unclear how to set up

### ISSUE THREAD

**Issue by willfaught** [getlago/lago-doc#125]
Path: /guide/security/sso

Doesn't explain how to set up Google SSO. I don't see anything in the settings.

**Comment by jdenquin** [comment]
@willfaught you should put those env var to make it work 
- `GOOGLE_AUTH_CLIENT_ID`
- `GOOGLE_AUTH_CLIENT_SECRET`

**Comment by willfaught** [comment]
Please also document how to set it up in the cloud UI.

**Comment by jdenquin** [comment]
@willfaught you have nothing to do in the UI, on the cloud, we only use our Google App

**Comment by willfaught** [comment]
What do you mean by your Google App?

Can we get Google SSO for our company org in the Lago Cloud service too?

**Comment by jdenquin** [comment]
you can't use your own Google Auth App limited to your organization for now.
We are actually working on adding Okta (where you can use your own oidc parameters) and, for later, SAML.

Would you want to use Google with your own organization and application?

**Comment by willfaught** [comment]
I want to be able to invite other users in my Google org by email to create an account in our Lago Cloud account, and they can sign in with their Google credentials. That's what I've meant by Google SSO. Is that what this doc means by Google SSO?

**Comment by jdenquin** [comment]
you can invite other users from Lago with their email, they will be able to join Lago with Google SSO. 
But if a user signup on Lago with the same domain as yours (used on your Google org), it will not be linked to your Lago Organization!

**Comment by willfaught** [comment]
OK, thanks for the clarification.
