### ISSUE TITLE
Issue on docs: disable Sign up property

### ISSUE THREAD

**Issue by algra4** [getlago/lago-doc#131]
Path: /guide/self-hosted/docker

The property to disable Sign up doesn't match with the code. 

Into the doc, the property is called `LAGO_DISABLE_SIGNUP` but into the code the property is `LAGO_SIGNUP_DISABLED` (c.f: https://github.com/getlago/lago-api/blob/efc555367c9836a657e46b33082bf9910edbd2dc/app/services/users_service.rb#L20C19-L20C39)

Can you update the doc with the right property?

**Comment by jdenquin** [comment]
This is an error on `api` side, it should be `LAGO_DISABLE_SIGNUP`
This will be fixed with : https://github.com/getlago/lago-api/pull/2256

**Comment by jdenquin** [comment]
This has been fixed and will be released during the next release!
