### ISSUE TITLE
Unclear what are the webhook URL HTTP status requirements

### ISSUE THREAD

**Issue by jstasiak** [getlago/lago-doc#142]
Hey,

I'm looking at https://docs.getlago.com/guide/webhooks at there's information about adding webhook URLs, viewing logs etc. but the page doesn't say what HTTP status needs to be returned by the webhook endpoint.

Is it HTTP 200 or all HTTP 2xx codes?

Or am I looking at a wrong page?

Thank you in advance.

**Comment by jdenquin** [comment]
Hello @jstasiak 

We support those response as success 
`RESPONSE_SUCCESS_CODES = [200, 201, 202, 204]`

Any other status will result in an error.

Here is a PR that fix it : https://github.com/getlago/lago-doc/pull/165

**Comment by jstasiak** [comment]
Everything's clear now, thank you for the response and the patch @jdenquin!
