### ISSUE TITLE
Duplicate usage event returns 422 error code

### ISSUE THREAD

**Issue by gyrolc** [getlago/lago-doc#279]
Path: /api-reference/events/usage

Duplicate usage events return a `422` error. This is not documented.

```
{
    "status": 422,
    "error": "Unprocessable Entity",
    "code": "validation_errors",
    "error_details": {
        "0": {
            "transaction_id": [
                "value_already_exist"
            ]
        },
}
```

**Comment by michaelponrajah** [comment]
Hello @gyrolc 👋 

The `422 - Unprocessable Entitiy` is already documented in this page
https://getlago.com/docs/api-reference/events/usage
![CleanShot 2024-12-18 at 18 35 55](https://github.com/user-attachments/assets/e02f1433-3009-4090-82aa-645364651a96)

But in the meantime, we've just created this PR to add this notion in our documentation, please follow this one here:
https://github.com/getlago/lago-doc/pull/281

Thanks again for this one 🙏

**Comment by michaelponrajah** [comment]
The changes have been deployed to production. 
Thanks again for pointing this out! 🙌
