### ISSUE TITLE
Document k8s/Helm installation

### ISSUE THREAD

**Issue by clouedoc** [getlago/lago-doc#8]
Hey!

I wish that the Helm charts were included in the documentation, as I was struggling to make my own chart for a while before I thought about looking into the main repo's issues: https://github.com/getlago/lago/issues/192

Searching for "kubernetes" or "helm" in the documentation doesn't yield any result

**Comment by sarkissianraffi** [comment]
Would this be helpful 👉 https://github.com/getlago/lago-helm-charts

**Comment by hadifarnoud** [comment]
any updates on this? want to deploy lago on k8s

**Comment by jdenquin** [comment]
@hadifarnoud @clouedoc We are using K8S with some custom charts on our Cloud.
We are working to make it available as an hosted helm chart, it should be available in the next weeks.
Do not hesitate to join our Slack community https://www.getlago.com/slack if you need more help around this

**Comment by sarkissianraffi** [comment]
This chart is now up-to-date. Feel free to provide your feedback: https://github.com/getlago/lago-helm-charts
